apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workload-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "workload-app-pods"
    spec:
      containers:
      - name: "web-app"
        image: chung123abc/webapp:v1.0
        ports: 
        - containerPort: 8080
