apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fake-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "fake-app-pods"
        purpose: "service-test"
    spec:
      containers:
      - name: "web-app"
        image: beekman9527/workload:latest
        ports: 
        - containerPort: 8080
